### ISSUE TITLE
submit changes to ostree-rs-ext

### ISSUE THREAD

**Issue by cgwalters** [hhd-dev/rechunk#1]
> Finally, this information is placed in a JSON file that is provided to a fork of [ostree-rs-ext](https://github.com/hhd-dev/ostree-rs-ext) that has been modified to follow custom rechunking plans with a JSON file as input.

Can you please at least PR these changes, even if draft form for visibility?

**Comment by antheas** [comment]
https://github.com/ostreedev/ostree-rs-ext/pull/652 done
