### ISSUE TITLE
Allow users to specify a custom meta file

### ISSUE THREAD

**Issue by p5** [hhd-dev/rechunk#5]
Some images will have different configurations to ublue, so it would be good if we can allow them to specify their own YAML files containing package groups, to be merged with the rechunk-provided one.  

For example, I would like to group my CNI plugins directory which is not installed via an RPM.  I would also like to group the 1Password RPMs and be able to have dedicated layer for Google Chrome.

If this action accepted an input such as `meta-file-path` or similar (I don't know what you wish to call this file), the user could specify their own groups and wouldn't need to try and have their specific packages or directories merged here.

**Comment by antheas** [comment]
Yes it is on the TODO, just has not happened yet. 

If your changes are small you can also PR them for now. Helps other users too.

**Comment by antheas** [comment]
https://github.com/hhd-dev/rechunk/releases/tag/v1.0.1 hopefully this works
